version: '3.2'

services:
  rdsync:
    container_name: "lineardev/rdsync"
    image: "lineardev/rdsync"
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["./rdsync"]
    ports:
      - "7045"
    volumes:
      - ./db:/app/rdsync/db
